[package]
name = "pend-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
env_logger = "0.11.8"
chrono = "0.4.40"
tokio = { version = "1.44.2", features = ["full"] }
pend-core = {path = "../pend-core"}
notify = "8.0.0"
